<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Задание 3</title><link rel="stylesheet" href="/goit-js-hw-11-promisification/task3.1d257160.css"></head><body> <section> <a href="/goit-js-hw-11-promisification/index.html">Главная</a> <div> <h1>Задание 3</h1> <p> Перепиши функцию <code>makeTransaction()</code> так, чтобы она не использовала callback-функции <code>onSuccess</code> и <code>onError</code>, а принимала всего один параметр <code>transaction</code> и возвращала промис. </p> <pre>
                        <code>
    const randomIntegerFromInterval = (min, max) => {
    return Math.floor(Math.random() * (max - min + 1) + min);
    };
    
    const makeTransaction = (transaction, onSuccess, onError) => {
    const delay = randomIntegerFromInterval(200, 500);
    
    setTimeout(() => {
    const canProcess = Math.random() > 0.3;
    
    if (canProcess) {
    onSuccess(transaction.id, delay);
    } else {
    onError(transaction.id);
    }
    }, delay);
    };
    
    const logSuccess = (id, time) => {
    console.log(`Transaction ${id} processed in ${time}ms`);
    };
    
    const logError = id => {
    console.warn(`Error processing transaction ${id}. Please try again later.`);
    };
    
    /*
    * Работает так
    */
    makeTransaction({ id: 70, amount: 150 }, logSuccess, logError);
    makeTransaction({ id: 71, amount: 230 }, logSuccess, logError);
    makeTransaction({ id: 72, amount: 75 }, logSuccess, logError);
    makeTransaction({ id: 73, amount: 100 }, logSuccess, logError);
    /*
    * Должно работать так
    */
    makeTransaction({ id: 70, amount: 150 })
    .then(logSuccess)
    .catch(logError);
    
    makeTransaction({ id: 71, amount: 230 })
    .then(logSuccess)
    .catch(logError);
    
    makeTransaction({ id: 72, amount: 75 })
    .then(logSuccess)
    .catch(logError);
    
    makeTransaction({ id: 73, amount: 100 })
    .then(logSuccess)
    .catch(logError);
                        </code>
                        </pre> </div> </section> <script src="/goit-js-hw-11-promisification/task3.5f7c9aab.js"></script> </body></html>